defaults:
  - local_system              : generic_lab
  - file_system               : common_fs
  - pipeline                  : assembly_pyilc_hm
  - scenario                  : scenario
  - splits                    : all  # If you aren't getting as many results as expected, check n_infer_cap as well
  - model/pyilc               : cnilc_512
  # - model/sim                 : sim_flex_fgs  # TODO: Try without this; remove if ok. Change from override in config_pyilc_on_planck
  - model/analysis            : basic_analysis
  - model/beam                : pyilc_beam
  - override hydra/job_logging: custom_log
  - _self_

# dataset_name   : ${scenario.map_fields}_${scenario.nside}_${splits.name}
dataset_name   : I_512_1850
working_dir    : "PyILC_CNILC/"
fig_model_name : "CNILC"
hydra:
  run:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}  # Should be the same as run.dir
    subdir     : ${hydra.job.num}
  verbose      : false

sim_work: Simulation_Working/

model:
  analysis:
    mask_sm_apo_size: 150
    mask_sm_apo_type: 'hp.smoothing'
  sim:
    include_cmb: false
    nside_sky: 2048

splits:
  Debias:
    n_sims: 10

# Settings below this point are used for interpolation.
# These are not to be used directly in python.
# They are picked up from here and MAY be used elsewhere in the yamls. Be careful, check assumptions!
# In the scenario yaml
nside          : 512
detectors      : [100, 143, 217, 353]
map_fields     : "I"

# In the pipeline yamls
# No epochs exist for PyILC method; use a placeholder:
use_epochs           : &epochs [""]
use_epochs_imgs      : *epochs
use_epochs_map_stats : *epochs
use_epochs_ps_stats  : *epochs

# Limit the number of simulations for which to generate figures
n_show_cap           : 3   # int: first n_sims; null: all sims (not recommended); list: particular sims by index
# Limit the number of simulations for which inference is run. In the splits yaml; null to run on all
n_infer_cap          : null
run_inference_on     : test  # Either "test" or "valid" ("train" should work, but is not recommended)
