# Do not name any yamls "default", "null", or "basic": these are reserved and will cause issues!
defaults:
  - config_pyilc
  - override pipeline: assembly_on_planck
  - override splits: "1-1"
  - _self_

working_dir        : "PyILC_on_Planck/"
fig_model_name     : "PyILC, On Planck"

planck_ds: PlanckAsDataset_${scenario.nside}
trained_wd: "PyILC_CNILC/"
